Resources:
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code: 
        ZipFile: |
          import json

          def lambda_handler(event, context):
              oper_dict = {
                  "add"       : event["input"]["input1"] + event["input"]["input2"]
                  "minus"     : event["input"]["input1"] - event["input"]["input2"]
                  "multiply"  : event["input"]["input1"] * event["input"]["input2"]
                  "divide"    : event["input"]["input1"] / event["input"]["input2"]
              }

              operation = event["operation"]

              try:
                  result = oper_dict[operation]
              except:
                  result = None

              response = {
                  "statusCode": 200
                  "body"      : json.dumps(result)
              }

              return response
      FunctionName: !Ref LambdaFunctionName
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Role: !GetAtt IAMRole.Arn

#  DynamoDBTable:

  APIGatewayRestAPI:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: !Ref APIName
    DependsOn:
      - LambdaFunction

  APIGatewayResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      ParentId: !GetAtt
        - APIGatewayRestAPI
        - RootResourceId
      PathPart: Calculator
    DependsOn:
      - APIGatewayRestAPI

  APIGatewayMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      ResourceId: !Ref APIGatewayResource
      HttpMethod: POST
      AuthorizationType: NONE
      MethodResponses:
        - StatusCode: 200
      Integration:
        Type: AWS
        IntegrationResponses:
          - StatusCode: 200
        IntegrationHttpMethod: POST
        Uri: !Sub
          - >-
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFuncNameArn}/invocations
          - LambdaFuncNameArn: !GetAtt LambdaFunction.Arn
    DependsOn:
      - APIGatewayResource


  APIGatewayDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref APIGatewayRestAPI
      StageName:
        Ref: EnvironmentName
    DependsOn:
      - APIGatewayMethod

  APIGatewayPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt LambdaFunction.Arn
      Principal: apigateway.amazonaws.com
    DependsOn:
      - APIGatewayDeployment

  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: Policty_api-lambda-db
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:CreateLogGroup'
                  - 'logs:PutLogEvents'
                Resource: '*' 


Parameters:
  APIName:
    Type: String
    Default: helloworld-serverless

  LambdaFunctionName:
    Type: String
    Default: Calculator

  EnvironmentName:
    Type: String
    Default: Dev